In [2]:
import numpy as np

In [2]:
a = np.array(5)

In [3]:
b = np.expand_dims(a, axis=0)

In [1]:
import torch

In [2]:
import torch
import torch.nn as nn

# 初始化数据
input = torch.randn(3, 5, requires_grad=True)  # 预测值，随机生成
target = torch.randn(3, 5)  # 实际目标值，随机生成

# 初始化 MSELoss 对象
mse_loss = nn.MSELoss()

# 计算损失
loss = mse_loss(input, target)

# 打印损失值
print(loss.item())

# 反向传播
loss.backward()

# 此时可以更新模型参数（例如，使用优化器）


0.4318118393421173


In [3]:
loss

tensor(0.4318, grad_fn=<MseLossBackward0>)

In [3]:
import numpy as np

In [5]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2],[3,4],[5,6]])
np.dot(a,b)

array([[22, 28],
       [49, 64]])

In [20]:
a = np.random.rand(2,3,4)
b = np.random.rand(2,4,6)

In [22]:
a.shape

(2, 3, 4)

In [11]:
a = torch.tensor([[1,2,3],[3,4,5]])
b = torch.tensor([[4,5,6],[9,8,7]])
a.div(b)

tensor([[0.2500, 0.4000, 0.5000],
        [0.3333, 0.5000, 0.7143]])

In [12]:
a.pow(4)

tensor([[  1,  16,  81],
        [ 81, 256, 625]])

In [32]:
torch.matmul(a,b.T)

tensor([[32, 46],
        [62, 94]])

In [37]:
c = torch.tensor([1,2,3])
d = torch.tensor([2,3,4])

In [39]:
c.matmul(d)

tensor(20)

In [38]:
torch.matmul(a,c)

tensor([14, 26])

In [23]:
np.dot(a,b).shape

(2, 3, 2, 6)

In [26]:
a = torch.rand(2,5,3,4)
b = torch.rand(2,5,4,6)

In [27]:
torch.matmul(a,b).size()

torch.Size([2, 5, 3, 6])

In [40]:
# 创建两个张量，并设置requires_grad=True以追踪梯度
a = torch.tensor([[1.0, 2.0], [3.0, 4.0]], requires_grad=True)
b = torch.tensor([[5.0, 6.0], [7.0, 8.0]], requires_grad=True)

# 执行矩阵乘法前向传播
result = torch.matmul(a, b)

# 模拟梯度并执行反向传播
result_grad = torch.tensor([[1.0, 0.0], [0.0, 1.0]])
result.backward(result_grad)

# 检查梯度
print("Gradient of a:", a.grad)
print("Gradient of b:", b.grad)

Gradient of a: tensor([[5., 7.],
        [6., 8.]])
Gradient of b: tensor([[1., 3.],
        [2., 4.]])


In [48]:
a = torch.tensor([1, 2, 3], dtype=torch.float32, requires_grad=True)
b = torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float32, requires_grad=True)
result = a.matmul(b)

result = a.matmul(b)
print(result)
result.backward(torch.tensor([1,1]))
print(a.grad)
print(b.grad)

tensor([22., 28.], grad_fn=<SqueezeBackward4>)
tensor([ 3.,  7., 11.])
tensor([[1., 1.],
        [2., 2.],
        [3., 3.]])


In [42]:
result

tensor([22, 28])

In [11]:
a*b

ValueError: operands could not be broadcast together with shapes (2,3,4) (2,4,6) 

In [2]:
# 创建两个一阶张量（向量）
A = torch.tensor([1, 2, 3])
B = torch.tensor([4, 5, 6])

# 使用torch.matmul()计算两个向量的内积
result = torch.matmul(A, B)

print(result) 

tensor(32)


In [7]:
C = torch.tensor([2])

In [9]:
A*3

tensor([3, 6, 9])

In [3]:
a = torch.tensor([[1,2],[3,4],[5,6]])

In [3]:
a = torch.from_numpy(np.array([[1,2,3],[4,5,6]])).reshape((3,2))

In [4]:
a

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [9]:
a.unsqueeze(-2).size()

torch.Size([3, 1, 2])

In [15]:
a = torch.tensor([[[1],[2]],[[3],[3]],[[4],[5]]])

In [16]:
a.squeeze(-1)

tensor([[1, 2],
        [3, 3],
        [4, 5]])

In [17]:
a.size()

torch.Size([3, 2, 1])

In [4]:
input_data = torch.tensor([1.0, 2.0, 3.0], requires_grad=False)
weights = torch.tensor([0.5], requires_grad=True)

In [5]:
predicted_torch = input_data * weights

In [6]:
predicted_torch

tensor([0.5000, 1.0000, 1.5000], grad_fn=<MulBackward0>)